{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.roleBinding.name | default (printf "%s-rolebinding" (include "deployment.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "deployment.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.roleBinding.roleRef | default .Values.rbac.role.name | default (printf "%s-role" (include "deployment.fullname" .)) }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}