{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.rbac.role.name | default (printf "%s-role" (include "deployment.fullname" .)) }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
rules:
{{- toYaml .Values.rbac.role.rules | nindent 2 }}
{{- end }}